CITY_OPTIONS = [
    "Almaty",
    "Astana",
    "Shymkent",
    "Aktobe",
    "Atyrau",
    "Aktau",
    "Karaganda",
    "Kostanay",
    "Kokshetau",
    "Kyzylorda",
    "Pavlodar",
    "Petropavl",
    "Semey",
    "Taraz",
    "Turkistan",
    "Taldykorgan",
    "Ust-Kamenogorsk",
    "Uralsk",
    "Zhezkazgan",
    "Abu Dhabi",
    "Addis Ababa",
    "Adelaide",
    "Alexandria",
    "Algiers",
    "Amman",
    "Amsterdam",
    "Ankara",
    "Antalya",
    "Ashgabat",
    "Athens",
    "Auckland",
    "Baghdad",
    "Baku",
    "Bali",
    "Baltimore",
    "Bangalore",
    "Bangkok",
    "Barcelona",
    "Basel",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Berlin",
    "Bishkek",
    "Bogota",
    "Boston",
    "Bratislava",
    "Brisbane",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Busan",
    "Cairo",
    "Calgary",
    "Cape Town",
    "Casablanca",
    "Chengdu",
    "Chicago",
    "Colombo",
    "Copenhagen",
    "Dallas",
    "Delhi",
    "Denver",
    "Dhaka",
    "Doha",
    "Dubai",
    "Dublin",
    "Dusseldorf",
    "Edinburgh",
    "Frankfurt",
    "Geneva",
    "Guangzhou",
    "Hamburg",
    "Hanoi",
    "Helsinki",
    "Ho Chi Minh City",
    "Hong Kong",
    "Honolulu",
    "Houston",
    "Istanbul",
    "Jakarta",
    "Jeddah",
    "Jerusalem",
    "Johannesburg",
    "Kabul",
    "Kampala",
    "Karachi",
    "Kathmandu",
    "Kazan",
    "Kharkiv",
    "Kigali",
    "Kuala Lumpur",
    "Kuwait City",
    "Kyiv",
    "Lagos",
    "Lahore",
    "Las Vegas",
    "Lima",
    "Lisbon",
    "London",
    "Los Angeles",
    "Lyon",
    "Madrid",
    "Manila",
    "Melbourne",
    "Mexico City",
    "Miami",
    "Milan",
    "Minsk",
    "Montreal",
    "Moscow",
    "Mumbai",
    "Munich",
    "Muscat",
    "Nagoya",
    "Nairobi",
    "Naples",
    "New Delhi",
    "New York",
    "Nice",
    "Novosibirsk",
    "Nur-Sultan",
    "Osaka",
    "Oslo",
    "Ottawa",
    "Paris",
    "Perth",
    "Phnom Penh",
    "Prague",
    "Qingdao",
    "Quebec City",
    "Riga",
    "Rio de Janeiro",
    "Riyadh",
    "Rome",
    "San Diego",
    "San Francisco",
    "Santiago",
    "Sao Paulo",
    "Seattle",
    "Seoul",
    "Shanghai",
    "Shenzhen",
    "Singapore",
    "Sofia",
    "Stockholm",
    "Sydney",
    "Taipei",
    "Tallinn",
    "Tashkent",
    "Tbilisi",
    "Tehran",
    "Tel Aviv",
    "Tokyo",
    "Toronto",
    "Tunis",
    "Ulaanbaatar",
    "Valencia",
    "Vancouver",
    "Venice",
    "Vienna",
    "Vilnius",
    "Warsaw",
    "Washington",
    "Wellington",
    "Yerevan",
    "Yokohama",
    "Zurich",
]

CITY_OPTIONS_SET = set(CITY_OPTIONS)
