# Generated by Django 5.0.6 on 2026-05-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('custom', 'Custom'), ('daily', 'Daily Challenge')], max_length=20)),
                ('rows', models.PositiveIntegerField()),
                ('cols', models.PositiveIntegerField()),
                ('mines', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], max_length=20)),
                ('time_seconds', models.PositiveIntegerField()),
                ('cells_revealed', models.PositiveIntegerField(default=0)),
                ('flags_placed', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('daily_seed', models.CharField(blank=True, default='', max_length=64)),
                ('brain_score_delta', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='games_game_user_id_92552f_idx'), models.Index(fields=['difficulty', 'result', 'time_seconds'], name='games_game_difficu_1b2931_idx'), models.Index(fields=['daily_seed', 'time_seconds'], name='games_game_daily_s_00b9fc_idx')],
            },
        ),
    ]
