# Generated by Django 5.0.6 on 2026-05-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('seed', models.CharField(max_length=64, unique=True)),
                ('rows', models.PositiveIntegerField(default=16)),
                ('cols', models.PositiveIntegerField(default=16)),
                ('mines', models.PositiveIntegerField(default=40)),
                ('mine_positions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='daily.dailychallenge')),
            ],
            options={
                'indexes': [models.Index(fields=['challenge', 'time_seconds'], name='daily_daily_challen_5d8dcc_idx')],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
